####################################################################
# !!! REMINDER !!!                                                 #
# Don't forget to run `manala up` each time you update this file ! #
####################################################################

manala:
    recipe: elao.app

##########
# System #
##########

system:
    version: 10
    hostname: symfony-demo.vm
    nginx:
        configs:
          # Php fpm
          - file: app_php_fpm
            template: configs/app_php_fpm.dev.j2
          # Gzip
          - file: app_gzip
            template: configs/app_gzip.dev.j2
          # App
          - file: app.conf
            config:
              - server:
                - server_name: ~.
                - root: /srv/app/public
                - access_log: /srv/log/nginx.access.log
                - error_log: /srv/log/nginx.error.log
                - include: conf.d/app_gzip
                - location /:
                  - try_files: $uri /index.php$is_args$args
                - location ~ ^/index\.php(/|$):
                  - include: conf.d/app_php_fpm
                  - internal;
    php:
        version: 7.4
        extensions:
          # Symfony
          - intl
          - curl
          - mbstring
          - xml
          # App
          - mysql
          - sqlite3
        configs:
          - file: app_opcache.ini
            template: configs/app_opcache.dev.j2
          - file: app.ini
            template: configs/app.dev.j2
            config:
              - date.timezone: UTC
    nodejs:
        version: 12
    mariadb:
        version: 10.4

    # files:
    #   # Single symfony app
    #   # ------------------
    #   - path: /srv/app/var/log
    #     src: /srv/log
    #     state: link_directory
    #     force: true
    #   - path: /srv/app/var/cache
    #     src: /srv/cache
    #     state: link_directory
    #     force: true
    #   # Multi apps
    #   # ----------
    #   - path: /srv/app/foo/var/log
    #     src: /srv/log/foo
    #     state: link_directory
    #     force: true
    #   - path: /srv/app/foo/var/cache
    #     src: /srv/cache/foo
    #     state: link_directory
    #     force: true
    # ssh:
    #     client:
    #         config:
    #           - Host *.elao.run:
    #             - User: app
    #             - ForwardAgent: true
